let dados = [
    {
      titulo: "Baroneza",
      imagem: "Baroneza.jpg",
      descricao: "A Baroneza é mais do que apenas uma locomotiva; ela representa um marco histórico fundamental para o Brasil. Construída em 1852 na Inglaterra e trazida para o país pelo visionário Barão de Mauá, a Baroneza realizou sua primeira viagem em território nacional em 30 de abril de 1854, inaugurando assim a era das ferrovias no Brasil.Com seu design elegante e construção robusta, a Baroneza não era apenas um meio de transporte, mas um símbolo de progresso e modernidade. Seus apitos agudos ecoavam pelos campos, anunciando uma nova era de desenvolvimento e conectando regiões antes isoladas. A locomotiva percorria um trajeto de 14,5 km, ligando o Porto de Mauá a Fragoso, na cidade de Magé, na Baixada Fluminense. A Baroneza foi muito mais do que uma máquina: ela foi um catalisador para o desenvolvimento econômico do país, facilitando o transporte de mercadorias e pessoas. Além disso, a locomotiva também desempenhou um papel importante na integração nacional, aproximando regiões distantes e fomentando o comércio. Hoje, a Baroneza é considerada um patrimônio histórico e cultural do Brasil, um testemunho vivo de uma época em que o ferro e o vapor moldavam o futuro do país.",
    },
    {
      titulo: "Baldwin",
      descricao: "A locomotiva Baldwin, fabricada pela Baldwin Locomotive Works nos Estados Unidos, foi um dos modelos mais populares e influentes nas ferrovias brasileiras. Sua robustez, versatilidade e confiabilidade a tornaram uma escolha frequente para diversas linhas ferroviárias do país.Produzidas em larga escala, as locomotivas Baldwin desempenharam um papel fundamental na expansão da malha ferroviária brasileira, transportando cargas e passageiros por vastas distâncias. Seus motores a vapor, potentes e eficientes, permitiam que essas máquinas superassem desafios como longas distâncias, terrenos acidentados e cargas pesadas. A Baldwin também se destacou por sua capacidade de adaptação, sendo utilizada em diversas configurações para atender às necessidades específicas de cada ferrovia.A herança das locomotivas Baldwin no Brasil é perene. Muitas delas foram preservadas em museus ferroviários, servindo como testemunhas de uma época marcada pela inovação tecnológica e pelo desenvolvimento industrial. A locomotiva Baldwin é, sem dúvida, um ícone da história ferroviária brasileira, representando um período em que o trem era o principal meio de transporte e o motor do progresso.",
    },
    {
      titulo: "Henschel & Sohn",
      descricao: "As locomotivas Henschel & Sohn, fabricadas na Alemanha, marcaram presença significativa nas ferrovias brasileiras. Conhecidas por sua robustez e potência, essas máquinas a vapor desempenharam um papel fundamental no transporte de cargas e passageiros em diversas regiões do país.A Henschel & Sohn produziu locomotivas de diferentes classes, adaptadas às diversas necessidades das ferrovias brasileiras. Seus projetos inovadores e a qualidade de seus componentes garantiram o bom desempenho dessas máquinas, mesmo em condições adversas. A confiabilidade das locomotivas Henschel & Sohn as tornou uma escolha popular entre as empresas ferroviárias brasileiras, que as utilizavam em linhas principais e secundárias.A presença das locomotivas Henschel & Sohn nas ferrovias brasileiras é um capítulo importante da história do transporte ferroviário no país. Muitas dessas máquinas ainda podem ser encontradas em museus ferroviários, servindo como testemunhas de uma época em que o apito da locomotiva a vapor era o som característico das viagens de trem.",
    },
    {
      titulo: "Mascot",
      descricao: "A locomotiva Mascot foi um verdadeiro ícone da Estrada de Ferro Central do Brasil. Construída com maestria e design elegante, a Mascot rapidamente se tornou um símbolo da modernidade ferroviária no país. Sua velocidade e potência a tornaram uma das locomotivas mais admiradas da época, transportando passageiros e cargas com agilidade e segurança.A elegância da Mascot era notável em cada detalhe, desde a pintura impecável até as linhas aerodinâmicas de sua carcaça. Seu apito característico ecoava pelos trilhos, anunciando sua chegada e despertando a admiração de todos que a viam passar. A locomotiva era um orgulho para a Estrada de Ferro Central do Brasil e para o país como um todo.Além de sua beleza estética, a Mascot era uma máquina extremamente eficiente. Sua capacidade de tração permitia que ela transportasse longos e pesados trens, contribuindo para o desenvolvimento econômico do Brasil. A locomotiva Mascot representa um capítulo importante da história ferroviária brasileira, um legado que continua a fascinar e inspirar até os dias de hoje.",
    },
    {
      titulo: "Mongul",
      descricao: "A locomotiva Mogul, com sua configuração de rodas 2-6-0 (duas rodas dianteiras, seis rodas motrizes), era uma das mais versáteis e populares nas ferrovias brasileiras. Sua robustez e capacidade de tração a tornaram ideal para diversas tarefas, desde a tração de trens de carga em linhas secundárias até manobras em pátios ferroviários.A Mogul era especialmente adequada para operar em linhas com curvas acentuadas e rampas íngremes, graças à sua distribuição de peso e à aderência proporcionada por suas seis rodas motrizes. Sua construção robusta permitia que suportasse as duras condições de trabalho nas ferrovias brasileiras, muitas vezes em regiões com clima adverso.A fama da Mogul se espalhou por todo o país, com diversas fabricantes, como a Baldwin e a Henschel & Sohn, produzindo modelos para as ferrovias brasileiras. A locomotiva Mogul deixou sua marca na história ferroviária do Brasil, sendo um símbolo de força e resistência, e continua a ser admirada por ferroviários e entusiastas até os dias de hoje.",
    },
    {
      titulo: "Pacific",
      descricao: "A locomotiva Pacific, com sua configuração de rodas 4-6-2, foi, por muitas décadas, a rainha indiscutível dos trens de passageiros. Seu design elegante e sua potência imbatível a tornaram um símbolo da era de ouro das viagens ferroviárias.Com suas grandes rodas motrizes e uma caldeira robusta, a Pacific era capaz de atingir velocidades impressionantes, proporcionando aos passageiros uma jornada suave e rápida. Sua configuração de três cilindros a tornava ainda mais potente, permitindo tracionar longos e pesados trens com facilidade. Muitas Pacifics eram equipadas com superaquecedores, que aumentavam a eficiência da locomotiva e reduziam o consumo de combustível.As Pacifics foram amplamente utilizadas em diversos países, incluindo os Estados Unidos, o Brasil e a Europa. No Brasil, essas majestosas máquinas puxavam trens de luxo entre as principais cidades, oferecendo aos passageiros um alto nível de conforto e sofisticação. Atualmente, poucas Pacifics ainda estão preservadas, tornando-as verdadeiras relíquias do passado e objetos de desejo para os amantes da história ferroviária.", 
    },
    {
      titulo: "Mikado",
      descricao: "A locomotiva Mikado foi um dos modelos mais populares e versáteis de locomotivas a vapor do século XX. Sua configuração de rodas 2-8-2, com um eixo condutor, quatro eixos acoplados e um eixo traseiro, a tornava ideal para tracionar longos e pesados trens de carga. A origem de seu nome é curiosa: em 1885, quando uma encomenda dessas locomotivas foi feita para os Caminhos de Ferro Japoneses, a opereta de Gilbert e Sullivan, era um grande sucesso nos Estados Unidos. A configuração das rodas dessas locomotivas, com a fornalha posicionada atrás do eixo condutor, permitia uma caldeira maior e mais eficiente, o que as tornava ideais para trabalhos pesados.No Brasil, as Mikados encontraram um terreno fértil para operar. Sua robustez e capacidade de tração as tornaram indispensáveis para o transporte de produtos agrícolas, minerais e industriais. Essas locomotivas podiam ser encontradas em diversas regiões do país, impulsionando o desenvolvimento econômico e integrando diferentes localidades. A imagem da Mikado, com sua imponente figura e o característico som do apito, ficou marcada na memória de gerações de brasileiros. Com o passar dos anos e a modernização das ferrovias, as locomotivas a vapor foram gradualmente substituídas por modelos a diesel e elétricos. No entanto, a Mikado deixou um legado importante na história ferroviária brasileira. Hoje, algumas dessas máquinas históricas são preservadas em museus e ferrovias turísticas, permitindo que o público admire sua beleza e aprenda sobre a importância do transporte ferroviário para o desenvolvimento do país.",
    },
    {
      titulo: "Consolidation",
      descricao: "A Consolidation, com sua configuração de rodas 2-8-0, foi um dos projetos de locomotiva a vapor mais bem-sucedidos e difundidos ao redor do mundo. Seu nome surgiu em homenagem à consolidação de diversas ferrovias americanas no século XIX. Essa locomotiva robusta e poderosa era especialmente projetada para tracionar longos e pesados trens de carga, tornando-se um símbolo da força e da resistência da era ferroviária a vapor.Com suas quatro rodas acopladas, a Consolidation oferecia excelente tração, permitindo que escalasse inclinações íngremes e transportasse cargas pesadas por longas distâncias. Sua construção robusta e simples a tornava uma máquina confiável e de fácil manutenção, ideal para as duras condições de trabalho nas ferrovias. A Consolidation era frequentemente utilizada em linhas com curvas acentuadas e em regiões montanhosas, onde sua potência e aderência eram fundamentais para superar os desafios do terreno.A versatilidade da Consolidation a tornou uma das locomotivas a vapor mais populares do mundo. Milhares de unidades foram construídas por diversas fabricantes, sendo utilizadas em diversos países. No Brasil, a Consolidation também deixou sua marca, operando em diversas linhas ferroviárias e contribuindo para o desenvolvimento do país. Embora tenha sido gradualmente substituída por locomotivas a diesel e elétricas, a Consolidation continua sendo lembrada como um ícone da era de ouro das ferrovias a vapor.",
    },
    {
      titulo: "Mountain",
      descricao: "A locomotiva Mountain, um verdadeiro gigante dos trilhos, era sinônimo de velocidade e potência no mundo ferroviário. Desenvolvida para atender à crescente demanda por trens de passageiros mais rápidos e confortáveis, a Mountain se tornou um ícone da era de ouro das viagens de trem.Com suas rodas grandes e sua caldeira robusta, a Mountain era capaz de alcançar velocidades impressionantes, tornando-a ideal para trens expressos de longa distância. Sua configuração de rodas, com uma roda motriz adicional em relação à configuração Pacific, proporcionava maior aderência aos trilhos, permitindo tracionar com segurança trens mais pesados.A locomotiva Mountain era uma máquina complexa e imponente, que exigia uma equipe altamente qualificada para operá-la. Seu design elegante e suas performances excepcionais a tornaram uma das locomotivas mais admiradas de sua época. No entanto, com o advento da tração diesel-elétrica, a era das locomotivas a vapor chegou ao fim, e as Mountains, assim como suas irmãs, foram gradualmente retiradas de serviço.",
    }
  ];


